apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: productpage-rollout
spec:
  strategy:
    canary:
      canaryService: productpage-canary
      stableService: productpage
      trafficRouting:
        istio:
          virtualServices:
          - name: bookinfo
            routes:
              - primary
          - name: bookinfo-canary
            routes:
              - secondary
      steps:
        - setWeight: 20
        - pause: {duration: 10}
        - setWeight: 40
        - pause: {duration: 10}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}    
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: productpage-v1